import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Izzeddin Samara",
  description: "Generated by create-flowbite-react",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className="bg-purple-200 dark:bg-gray-900"
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
